server:
  port: ${PORT:8080}

app:
  token:
    secret-key: ${JWT_SECRET_KEY:RmlsaXBlbnNlcyAyOjEyIGRlc2Vudm9sdmVpIGEgdm9zc2Egc2FsdmHDp8OjbyBjb20gdGVtb3IgZSB0cmVtb3I=}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:stateless_auth}?createDatabaseIfNotExist=true
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}

    tomcat:
      max-active: 3

  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgresql
  
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        formatSql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
